### ISSUE TITLE
cloudformation error

### ISSUE THREAD

**Issue by nimendra** [tkgregory/spring-boot-api-example#3]
Noticed the gradle rollback, but even with that
```
 > startup failed:
  General error during semantic analysis: Unsupported class file major version 60

  java.lang.IllegalArgumentException: Unsupported class file major version 60
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)

```

**Comment by tkgregory** [comment]
Hi. Sorry for the slow response. I think this is caused by building with a more recent version of Java. I upgraded to Gradle 7.2 and fixed the Java version at 17. Let me know if the issue went away. Thanks.
